version: "3.9"
services:
  pgsectest:
    build: .
    command:
      - pgsectest
      - /host/testdata/tests1.yaml
    environment:
      PGUSER: postgres
      PGDATABASE: postgres
      PGHOST: postgres
      PGSSLCERT: /host/config/tls/int_client/certs/postgres.pem
      PGSSLKEY: /host/config/tls/int_client/private/postgres.key.pem
      PGSSLROOTCERT: /host/config/tls/int_server/certs/ca-chain-bundle.cert.pem
    volumes:
    - ./:/host
  postgres:
    image: postgres:15
    command:
      - postgres
      - '-c'
      - 'config_file=/host/config/postgresql.conf'
    environment:
      POSTGRES_PASSWORD: pgsectest
      POSTGRES_HOST_AUTH_METHOD: cert
#    ports:
#    - "5432:5432"
    volumes:
    - ./:/host
    - ./config/postgresql.conf:/etc/postgresql/postgresql.conf
  chainsmith:
    image: mannemsolutions/chainsmith
    volumes:
    - ./:/host
    environment:
      CHAINSMITH_CONFIG: /host/config/chainsmith.yml
