name: Golang-security-action

on:
  push:
    branches:
      - master
      - develop
      - main
  pull_request:

jobs:
    golang-security-action:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: ynniss/golang-security-action@master
              with:
                CODE_PATH: "./"
